### PR TITLE
Update localizations (en-GB, fr, ru)

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
Not sure if there will be updates before the deadline, but I wanted to make sure we include updates to localization in the repo.

**Comment by jonathanKingston** [comment]
Thanks!

**Comment by flodolo** [comment]
We will need to make sure to pick up the latest localization before the release. Is a PR like this one OK, or do you prefer to do it on your side?

**Comment by jonathanKingston** [comment]
@flodolo this is great yeah, please be aware I had to rewrite the history to be able to make a release branch to make a PR. If you need to update things refork and work from the `shield-study` branch.

**Comment by flodolo** [comment]
> @flodolo this is great yeah, please be aware I had to rewrite the history to be able to make a release branch to make a PR. If you need to update things refork and work from the shield-study branch.

OK, thanks for the heads-up

**Pull request merged**
